
'use client';

import { useState, useEffect, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Sparkles, RefreshCw } from 'lucide-react';
import { generateWellnessSummary, type WellnessSummaryInput } from '@/ai/flows/wellness-summary';
import type { VitalSigns } from '@/lib/types';

interface WellnessSummaryProps {
  vitalSigns: VitalSigns | null;
}

export function WellnessSummary({ vitalSigns }: WellnessSummaryProps) {
  const [summary, setSummary] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const fetchSummary = useCallback(async () => {
    if (!vitalSigns) return;

    setIsLoading(true);
    setError(null);
    try {
      const result = await generateWellnessSummary({ vitalSigns });
      setSummary(result.summary);
    } catch (e) {
      console.error("Failed to generate wellness summary:", e);
      setError("Could not load summary. Please try again.");
    } finally {
      setIsLoading(false);
    }
  }, [vitalSigns]);

  useEffect(() => {
    // Initially load the summary when the component mounts and vital signs are available.
    fetchSummary();
  }, [fetchSummary]);

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Sparkles className="h-5 w-5 text-primary" />
          AI Wellness Summary
        </CardTitle>
        <CardDescription>
          A brief overview of the latest vital signs data, generated by AI.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {isLoading && (
            <div className="space-y-2">
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-full" />
              <Skeleton className="h-4 w-3/4" />
            </div>
          )}
          {error && <p className="text-sm text-destructive">{error}</p>}
          {summary && !isLoading && <p className="text-sm text-foreground">{summary}</p>}
          
          <Button onClick={fetchSummary} disabled={isLoading || !vitalSigns}>
            <RefreshCw className={`mr-2 h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
            {isLoading ? 'Generating...' : 'Refresh Summary'}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

    